language: python

python: "3.5"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

jobs:
  include:
    - name: "Normal tests and pre-commit checks"
      env:
        - JOB_RUN_CMD="make ci-job"
        - DEPLOY_FROM_THIS_JOB="true"

before_install:
  # Update docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Reconfigure docker to be more efficient
  - |
    echo '{
      "experimental": true,
      "storage-driver": "overlay2",
      "max-concurrent-downloads": 50,
      "max-concurrent-uploads": 50
    }' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  # Pull cached docker image
  - docker pull rlworkgroup/metaworld-ci:latest

install:
  - tag="rlworkgroup/metaworld-ci:${TRAVIS_BUILD_NUMBER}"
  - TAG="${tag}" make build-ci

before_script:
  - ci_env="$(bash <(curl -s https://codecov.io/env))"

script:
  - ADD_ARGS="${ci_env}" TAG="${tag}" make run-ci RUN_CMD="${JOB_RUN_CMD}"

deploy:
  provider: script
  script: TAG="${tag}" make ci-deploy-docker
  on:
    branch: master
    condition: $DEPLOY_FROM_THIS_JOB = true

notifications:
  email: false
